name: Update PoE2 News

on:
  schedule:
    # 北京时间每天上午 9 点执行 (UTC 1:00)
    - cron: '0 1 * * *'
  workflow_dispatch: # 允许手动点击按钮触发

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run News Crawler (With Details)
        env:
          CI: true
          OSS_REGION: oss-cn-hangzhou
          OSS_BUCKET: poe2-all-class
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          NODE_ENV: production
        run: npm run crawl:news:all
